
### get the list of all products
GET http://localhost:3000/products
Content-Type: application/json



### create a product

POST  http://localhost:3000/products
Content-Type:application/json

{
    "name": "iphone 12 pro",
    "price": 15000
}


### get a product by ID
GET http://localhost:3000/products/6468c8834e3266241b94bde7




###  update a product by ID

PATCH  http://localhost:3000/products/646683d8c3ece511b5823bcd
Content-Type: application/json

{
    "name":"update",
    "price":2000000
}
  

  

###    delete a product by ID

DELETE  http://localhost:3000/products/6468cb525eb8730c6e281059



